export const users = [
  {
    scenario: "Full Hobbies",
    name: "Ivo",
    email: "ivo@ivo.com",
    password: "password123",
    country: "portugal",
    gender: "Male",
    hobbies: [
      "Read books",
      "Travel",
      "Video Games",
      "Sports",
      "Movies",
      "Board Games",
    ],
  },
  {
    scenario: "No Hobbies",
    name: "Rafa",
    email: "ivo@ivo.com",
    password: "password123",
    country: "mexico",
    gender: "Male",
    hobbies: [],
  },
  {
    scenario: "Multiple Hobbies",
    name: "Silva",
    email: "ivo@ivo.com",
    password: "password123",
    country: "canada",
    gender: "Female",
    hobbies: ["Read books", "Travel", "Video Games", "Sports"],
  },
  {
    scenario: "Others",
    name: "Camões",
    email: "ivo@ivo.com",
    password: "password123",
    country: "brazil",
    gender: "Other",
    hobbies: [
      "Read books",
      "Travel",
      "Video Games",
      "Sports",
      "Movies",
      "Board Games",
    ],
  },
  {
    scenario: "Murica",
    name: "Vasco",
    email: "ivo@ivo.com",
    password: "password123",
    country: "usa",
    gender: "Other",
    hobbies: ["Read books", "Travel", "Video Games", "Sports"],
  },
];

export const failedFormValidationMessages = {
  name: "The name field is required.",
  email: "The email field is required.",
  password: "The password field is required.",
  country: "The country field is required.",
  gender: "The gender field is required.",
};
